/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package census.presentation.dialogs;

import census.business.ClientProfilesService;
import census.business.api.BusinessException;
import census.business.api.SecurityException;
import census.business.ClientsService;
import census.business.SessionsService;
import census.business.api.ValidationException;
import census.business.dto.ClientDTO;
import census.business.dto.ClientProfileDTO;
import census.presentation.CensusFrame;
import java.beans.Beans;
import java.util.ResourceBundle;
import javax.swing.JFrame;

/**
 *
 * @author daniel
 */
public class RegisterClientDialog extends CensusDialog {
    private ResourceBundle bundle = ResourceBundle.getBundle("census/presentation/resources/Strings");

    /*
     * Business
     */
    private ClientsService clientsService;
    private ClientDTO client;
    private Boolean isClientRegistered;
    private ClientProfilesService clientProfilesService;
    private ClientProfileDTO clientProfile;

    /**
     * Creates new form RegisterClientDialog
     */
    public RegisterClientDialog(JFrame parent) {
        super(parent, true);

        if (!Beans.isDesignTime()) {
            clientsService = ClientsService.getInstance();
            client = clientsService.getTemplateClient();
            isClientRegistered = false;

            clientProfilesService = ClientProfilesService.getInstance();
            clientProfile = new ClientProfileDTO();
        }

        initComponents();

        if (!Beans.isDesignTime()) {
            setLocationRelativeTo(parent);
            attachProfileCheckBoxStateChanged(null);
            clientPanel.setClient(client);
            clientProfilePanel.setClientProfile(clientProfile);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientPanel = new census.presentation.blocks.ClientPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        clientProfilePanel = new census.presentation.blocks.ClientProfilePanel();
        optionsPanel = new javax.swing.JPanel();
        attachProfileCheckBox = new javax.swing.JCheckBox();
        openFinancialActivityCheckBox = new javax.swing.JCheckBox();
        openAttendanceCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(bundle.getString("Title.RegisterClient")); // NOI18N
        setResizable(false);

        clientPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Text.BasicInformation"))); // NOI18N

        okButton.setText(bundle.getString("Button.Ok")); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(bundle.getString("Button.Cancel")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        clientProfilePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Text.ProfileInformation"))); // NOI18N

        optionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Text.AdditionalActions"))); // NOI18N

        attachProfileCheckBox.setText(bundle.getString("CheckBox.AttackProfileNow")); // NOI18N
        attachProfileCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                attachProfileCheckBoxStateChanged(evt);
            }
        });

        openFinancialActivityCheckBox.setText(bundle.getString("CheckBox.OpenOrderUponCompletion")); // NOI18N

        openAttendanceCheckBox.setText(bundle.getString("CheckBox.OpenAttendanceUponCompletion")); // NOI18N

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attachProfileCheckBox)
                    .addComponent(openFinancialActivityCheckBox)
                    .addComponent(openAttendanceCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attachProfileCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openFinancialActivityCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openAttendanceCheckBox)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton)
                            .addComponent(okButton)))
                    .addComponent(clientProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        if (!clientPanel.isFormValid() || (attachProfileCheckBox.isSelected() && !clientProfilePanel.isFormValid())) {
            return;
        }

        try {
            if (!isClientRegistered) {
                // TODO: security check
                Short clientId = clientsService.registerClient(client, SessionsService.getInstance().getPermissionsLevel().equals(SessionsService.PL_ALL));
                client.setId(clientId);
                isClientRegistered = true;
            }
            if (attachProfileCheckBox.isSelected()) {
                clientProfile.setId(client.getId());
                clientProfilesService.attachClientProfile(clientProfile);
            }
        } catch (SecurityException ex) {
            // Should not be thrown with current implemetation
            setResult(EditOrderDialog.RESULT_EXCEPTION);
            setException(new RuntimeException(ex));
            dispose();
            return;
        } catch (ValidationException ex) {
            CensusFrame.getGlobalCensusExceptionListenersStack().peek().processException(ex);
            return;
        } catch (BusinessException ex) {
            CensusFrame.getGlobalCensusExceptionListenersStack().peek().processException(ex);
            return;
        } catch (RuntimeException ex) {
            /*
             * The exception is unexpected. We got to shutdown the dialog for
             * the state of the transaction is now unknown.
             */
            setResult(EditOrderDialog.RESULT_EXCEPTION);
            setException(ex);
            dispose();
            return;
        }

        setClientId(client.getId());
        setEditFinancialActivityDialogRequested(openFinancialActivityCheckBox.isSelected());
        setOpenAttendanceDialogRequested(openAttendanceCheckBox.isSelected());
        setResult(CensusDialog.RESULT_OK);
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setResult(CensusDialog.RESULT_CANCEL);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void attachProfileCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_attachProfileCheckBoxStateChanged
        if (attachProfileCheckBox.isSelected() != clientProfilePanel.isVisible()) {
            clientProfilePanel.setVisible(attachProfileCheckBox.isSelected());
            pack();
        }
    }//GEN-LAST:event_attachProfileCheckBoxStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox attachProfileCheckBox;
    private javax.swing.JButton cancelButton;
    private census.presentation.blocks.ClientPanel clientPanel;
    private census.presentation.blocks.ClientProfilePanel clientProfilePanel;
    private javax.swing.JButton okButton;
    private javax.swing.JCheckBox openAttendanceCheckBox;
    private javax.swing.JCheckBox openFinancialActivityCheckBox;
    private javax.swing.JPanel optionsPanel;
    // End of variables declaration//GEN-END:variables

    public Short getClientId() {
        return clientId;
    }

    public void setClientId(Short clientId) {
        this.clientId = clientId;
    }

    public Boolean isOpenAttendanceDialogRequested() {
        return openAttendanceDialogRequested;
    }

    public void setOpenAttendanceDialogRequested(Boolean attendanceDialogRequested) {
        this.openAttendanceDialogRequested = attendanceDialogRequested;
    }

    public Boolean isEditFinancialActivityDialogRequested() {
        return editFinancialActivityDialogRequested;
    }

    public void setEditFinancialActivityDialogRequested(Boolean editFinancialActivityDialogRequested) {
        this.editFinancialActivityDialogRequested = editFinancialActivityDialogRequested;
    }
    private Boolean editFinancialActivityDialogRequested;
    private Boolean openAttendanceDialogRequested;
    private Short clientId;
}
