/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package census.presentation.dialogs;

import census.business.ItemsService;
import census.business.api.BusinessException;
import census.business.api.SecurityException;
import census.business.api.ValidationException;
import census.business.dto.ItemDTO;
import census.presentation.CensusFrame;
import census.presentation.util.ItemsTableModel;
import census.presentation.util.ItemsTableModel.Column;
import java.beans.Beans;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author daniel
 */
public class ManageItemsDialog extends CensusDialog {

    private ResourceBundle bundle = ResourceBundle.getBundle("census/presentation/resources/Strings");

    /*
     * Business
     */
    private List<ItemDTO> items;
    private Boolean isNew;

    /*
     * Presentation
     */
    private ItemsTableModel itemsTableModel;

    /**
     * Creates new form ItemsDialog
     */
    public ManageItemsDialog(JFrame parent) {
        super(parent, true);
        items = ItemsService.getInstance().getPureItems();

        initComponents();

        if (!Beans.isDesignTime()) {

            /*
             * Listens to the table to know when to enable the Edit button
             */
            itemsTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

                @Override
                public void valueChanged(ListSelectionEvent e) {
                    if (itemPanel.getItem() != null) {
                        return;
                    }
                    
                         
                    // There has to be exactly one selected item for editing to take place
                    if (itemsTable.getSelectedRowCount() == 1) {
                        editButton.setEnabled(true);
                    } else {
                        editButton.setEnabled(false);
                    }
                }
            });

            editingApplyButton.setEnabled(false);
            editingCancelButton.setEnabled(false);
        }

        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        itemsScrollPane = new javax.swing.JScrollPane();
        itemsTable = new javax.swing.JTable();
        cancelButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        itemDetailsPanel = new javax.swing.JPanel();
        editingApplyButton = new javax.swing.JButton();
        editingCancelButton = new javax.swing.JButton();
        itemPanel = new census.presentation.blocks.ItemPanel();
        removeButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(bundle.getString("Title.ManageItems")); // NOI18N
        setResizable(false);

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/census/presentation/resources/plus32.png"))); // NOI18N
        addButton.setText(bundle.getString("Button.Add")); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        Column[] columns =
        new Column[]{Column.TITLE,
            Column.QUANTITY,
            Column.PRICE,
            Column.BARCODE};
        itemsTableModel = new ItemsTableModel(columns);
        itemsTableModel.setItems(items);
        itemsTable.setModel(itemsTableModel);
        itemsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        itemsScrollPane.setViewportView(itemsTable);

        cancelButton.setText(bundle.getString("Button.Cancel")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/census/presentation/resources/edit32.png"))); // NOI18N
        editButton.setText(bundle.getString("Button.Edit")); // NOI18N
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        itemDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Text.ItemDetails"))); // NOI18N

        editingApplyButton.setText(bundle.getString("Button.Apply")); // NOI18N
        editingApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editingApplyButtonActionPerformed(evt);
            }
        });

        editingCancelButton.setText(bundle.getString("Button.Cancel")); // NOI18N
        editingCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editingCancelButtonActionPerformed(evt);
            }
        });

        itemPanel.setItem(null);

        javax.swing.GroupLayout itemDetailsPanelLayout = new javax.swing.GroupLayout(itemDetailsPanel);
        itemDetailsPanel.setLayout(itemDetailsPanelLayout);
        itemDetailsPanelLayout.setHorizontalGroup(
            itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editingApplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editingCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                .addComponent(itemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        itemDetailsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {editingApplyButton, editingCancelButton});

        itemDetailsPanelLayout.setVerticalGroup(
            itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                .addComponent(itemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editingCancelButton)
                    .addComponent(editingApplyButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        removeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/census/presentation/resources/remove32.png"))); // NOI18N
        removeButton.setText(bundle.getString("Button.Remove")); // NOI18N
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        getRootPane().setDefaultButton(okButton);
        okButton.setText(bundle.getString("Button.Ok")); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itemsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itemDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton)
                            .addComponent(okButton)))
                    .addComponent(itemsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        isNew = true;
        itemPanel.setItem(new ItemDTO());

        itemsTable.getSelectionModel().clearSelection();

        editingApplyButton.setEnabled(true);
        editingCancelButton.setEnabled(true);
        cancelButton.setEnabled(false);
        okButton.setEnabled(false);
        addButton.setEnabled(false);
        removeButton.setEnabled(false);
        editButton.setEnabled(false);
    }//GEN-LAST:event_addButtonActionPerformed

    private void editingApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editingApplyButtonActionPerformed
        if (!itemPanel.isFormValid()) {
            return;
        }

        try {
            if (isNew) {
                ItemsService.getInstance().addItem(itemPanel.getItem());
            } else {
                ItemsService.getInstance().updateItem(itemPanel.getItem());
            }
        } catch (SecurityException | ValidationException ex) {
            CensusFrame.getGlobalCensusExceptionListenersStack().peek().processException(ex);
            return;
        } catch (RuntimeException ex) {
            /*
             * The exception is unexpected. We got to shutdown the dialog for
             * the state of the transaction is now unknown.
             */
            setResult(EditOrderDialog.RESULT_EXCEPTION);
            setException(ex);
            dispose();
            return;
        }

        itemPanel.setItem(null);
        items = ItemsService.getInstance().getPureItems();
        itemsTableModel.setItems(items);
        
        editingApplyButton.setEnabled(false);
        editingCancelButton.setEnabled(false);
        cancelButton.setEnabled(true);
        okButton.setEnabled(true);
        addButton.setEnabled(true);
        removeButton.setEnabled(true);
    }//GEN-LAST:event_editingApplyButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if (JOptionPane.NO_OPTION == JOptionPane.showConfirmDialog(this, bundle.getString("Message.AreYouSureYouWantToCancelChanges"), bundle.getString("Title.Confirmation"), JOptionPane.YES_NO_OPTION)) {
            return;
        }

        setResult(RESULT_CANCEL);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        isNew = false;
        itemPanel.setItem(items.get(itemsTable.getSelectedRow()));

        editingApplyButton.setEnabled(true);
        editingCancelButton.setEnabled(true);
        cancelButton.setEnabled(false);
        okButton.setEnabled(false);
        addButton.setEnabled(false);
        removeButton.setEnabled(false);
        editButton.setEnabled(false);
    }//GEN-LAST:event_editButtonActionPerformed

    private void editingCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editingCancelButtonActionPerformed
        itemPanel.setItem(null);
        
        editingApplyButton.setEnabled(false);
        editingCancelButton.setEnabled(false);
        cancelButton.setEnabled(true);
        okButton.setEnabled(true);
        addButton.setEnabled(true);
        removeButton.setEnabled(true);
        editButton.setEnabled(true);
    }//GEN-LAST:event_editingCancelButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        if (JOptionPane.NO_OPTION == JOptionPane.showConfirmDialog(this, bundle.getString("Message.AreYouSureYouWantToRemoveItems"), bundle.getString("Title.Confirmation"), JOptionPane.YES_NO_OPTION)) {
            return;
        }

        ItemsService itemsService = ItemsService.getInstance();

        for (int index : itemsTable.getSelectedRows()) {
            try {
                try {
                    itemsService.removeItem(items.get(index).getId());
                } catch (ValidationException ex) {
                    throw new RuntimeException(ex);
                } catch (BusinessException ex) {
                    CensusFrame.getGlobalCensusExceptionListenersStack().peek().processException(ex);
                } catch (SecurityException ex) {
                    throw new RuntimeException(ex);
                }
            } catch (RuntimeException ex) {
                /*
                 * The exception is unexpected. We got to shutdown the dialog
                 * for the state of the transaction is now unknown.
                 */
                setResult(EditOrderDialog.RESULT_EXCEPTION);
                setException(ex);
                dispose();
                return;
            }
        }

        items = itemsService.getPureItems();
        itemsTableModel.setItems(items);
    }//GEN-LAST:event_removeButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        setResult(RESULT_OK);
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton editingApplyButton;
    private javax.swing.JButton editingCancelButton;
    private javax.swing.JPanel itemDetailsPanel;
    private census.presentation.blocks.ItemPanel itemPanel;
    private javax.swing.JScrollPane itemsScrollPane;
    private javax.swing.JTable itemsTable;
    private javax.swing.JButton okButton;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
